<?php

/**
* samumaretya / productSlider
* samumaretiya@gmail.com
* skype : samumaretiya
 * Copyright © Zealous Commerce. All rights reserved.
 * This product is licensed per Magento install
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\Slider;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Productslider\ViewModel\HomePageProductList;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Wishlist $wishlistViewModel */
/** @var ProductCompare $compareViewModel */
/** @var Store $storeViewModel */
/** @var Slider $sliderViewModel */
/** @var StoreConfig $storeConfig */
/** @var HomePageProductList $homePageProductList */

$sliderViewModel      = $viewModels->require(Slider::class);
$wishlistViewModel    = $viewModels->require(Wishlist::class);
$compareViewModel     = $viewModels->require(ProductCompare::class);
$storeViewModel       = $viewModels->require(Store::class);
$storeConfig          = $viewModels->require(StoreConfig::class);
$homePageProductList  = $viewModels->require(HomePageProductList::class);

$headingTag        = $block->getData('heading_tag') ?: 'h3';
$hideDetails       = $block->getData('hide_details') ?? false;
$hideRatingSummary = $block->getData('hide_rating_summary') ?? false;
$type              = $block->getData('type');
$itemTemplate      = $block->getData('item_template') ?? 'Magento_Catalog::product/list/item.phtml';
$containerTemplate = $block->getData('container_template')
    ?? 'Hyva_Productslider::product/slider/product-slider-container.phtml';

$title       = $storeConfig->getStoreConfig('zealous_ecommerce_homepage/slider/title');
$productSkus = $storeConfig->getStoreConfig('zealous_ecommerce_homepage/slider/product_sku');
$skusFilter  = explode(',', $productSkus);
$items       = $homePageProductList->createSliderProductCollection($skusFilter);

$sliderHtml = $sliderViewModel->getSliderForItems($itemTemplate, $items, $containerTemplate)
    ->setData('hide_details', $hideDetails)
    ->setData('hide_rating_summary', $hideRatingSummary)
    ->setData('title', $title)
    ->setData('item_relation_type', $type)
    ->setData('heading_tag', $headingTag)
    ->toHtml();

if (empty($sliderHtml)) {
    return '';
}
?>
<div class="product-slider">
    <div>
        <?= /* @noEscape */ $sliderHtml ?>
    </div>
    <script>
        'use strict';
        window.addEventListener('DOMContentLoaded', function() {
            if (!window.productSliderEventHandlerInitialized) {
                window.productSliderEventHandlerInitialized = true;

                <?php if ($wishlistViewModel->isEnabled()) : ?>
                    window.addEventListener('product-add-to-wishlist', (event) => {
                        const formKey = hyva.getFormKey();
                        const postUrl = BASE_URL + 'wishlist/index/add/';
                        const productId = event.detail.productId;

                        fetch(postUrl, {
                            "headers": {
                                "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                            },
                            "body": "form_key=" + formKey + "&product=" + productId + "&uenc=" + hyva.getUenc(),
                            "method": "POST",
                            "mode": "cors",
                            "credentials": "include"
                        }).then(function(response) {
                            if (response.redirected) {
                                window.location.href = response.url;
                            } else if (response.ok) {
                                return response.json();
                            } else {
                                typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                    [{
                                        type: "warning",
                                        text: "<?= $escaper->escapeHtml(__('Could not add item to wishlist.')) ?>"
                                    }], 5000
                                );
                            }
                        }).then(function(result) {
                            if (!result) {
                                return
                            }
                            typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                [{
                                    type: (result.success) ? "success" : "error",
                                    text: (result.success) ?
                                        "<?=
                                            $escaper->escapeHtml(
                                                __("%1 has been added to your Wish List.", __("Product"))
                                            )
                                            ?>" : result.error_message
                                }], 5000
                            );
                            window.dispatchEvent(new CustomEvent("reload-customer-section-data"));
                        }).catch(function(error) {
                            typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                [{
                                    type: "error",
                                    text: error
                                }], 5000
                            );
                        });
                    })
                <?php endif; ?>

                <?php if ($compareViewModel->showInProductList()) : ?>
                    window.addEventListener('product-add-to-compare', (event) => {
                        const productId = event.detail.productId;
                        hyva.postForm({
                            action: BASE_URL + 'catalog/product_compare/add/',
                            data: {
                                product: productId
                            }
                        })
                    })
                <?php endif; ?>
            }
        });
    </script>
</div>